### PR TITLE
Fix urls.py so it works with django > 1.8

### PR DESCRIPTION
**Pull request by alchris**
The django.conf.urls.patterns function was removed in django.

Fixes jgiannuzzi/taiga-contrib-saml-auth#1

Improves pull request #3

### CODE REVIEW

**Comment by jgiannuzzi** [comment]
Thanks for your PR, @alchris!

**Comment by fghaas** [comment]
Thanks for merging this, @jgiannuzzi! Would you consider cutting a 1.0.2 release? With this fix in place, Django 1.9+ installations should be happy, and right now, a fresh `taiga-back` install defaults to Django 1.11.

**Comment by jgiannuzzi** [comment]
Hey @fghaas, I just released 1.0.2 on pypi.

**Comment by fghaas** [comment]
Fantastic, thanks a bunch!

**Pull request merged**
